# Nama : Silvia Rohmadina
# NIM    : 200601110038

# File Handling

In [1]:
f = open("Contoh.txt", "r")
print(f.read())

Halo, saya adalah mahasiswa UIN MALIKI.
Nama saya Silvia Rohmadina, NIM 200601110038.
Pagi ini saya telah mengikuti kelas PPK I.Now the file has more content!


In [2]:
f = open("Contoh.txt", "r")
print(f.read(20))

Halo, saya adalah ma


In [3]:
f = open("Contoh.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f = open("Contoh.txt", "r")
print(f.read())

Halo, saya adalah mahasiswa UIN MALIKI.
Nama saya Silvia Rohmadina, NIM 200601110038.
Pagi ini saya telah mengikuti kelas PPK I.Now the file has more content!Now the file has more content!


## Chapter 5

### 5.1 Pendahuluan

In [4]:
import numpy as np
a = np. arange (15).reshape (3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a. shape

(3, 5)

In [6]:
 a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array ([6 , 7 , 8])
b

array([6, 7, 8])

In [12]:
 type (b)

numpy.ndarray

### 5.2 Membuat Array

In [13]:
import numpy as np
a = np.array ([2 ,3 ,4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.array ([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [16]:
b = np.array ([(1.5 ,2 ,3),(4 ,5 ,6) ])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
c = np.array ( [ [1 ,2] , [3 ,4] ] , dtype = complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
np. zeros ( (3 ,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np. ones ( (2 ,3 ,4) , dtype =np. int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np. empty((2 ,3)) #uninitialized ,output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
np. arange (10 ,30 ,5 )

array([10, 15, 20, 25])

In [22]:
np. arange (0 ,2 ,0.3 ) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
from numpy import pi
np. linspace (0 ,2 ,9) #9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np. linspace (0 ,2*pi ,100 ) # useful to evaluate function at lots of points
f = np.sin (x)

### 5.3 Menampilkan Array

In [25]:
a = np. arange (6) #1d array
print (a)

[0 1 2 3 4 5]


In [26]:
b = np. arange (12).reshape (4 ,3) # 2d array
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
c = np.arange(24).reshape (2 ,3 ,4) # 3d array
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
print (np. arange (10000))

[   0    1    2 ... 9997 9998 9999]


In [29]:
print (np. arange (10000) . reshape (100 ,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [30]:
np. set_printoptions ( threshold = 3)